### PR TITLE
Fix SeekBar no longer dragging

### LINKED ISSUE #24: compose-bom 2024.02.00 breaks hold and drag functionality of the slider
**Summary:**
Upgrading to latest `compose-bom` (2024.02.00) seem to partly break the slider and no longer allows holding and dragging the progress bar.

**Steps to Reproduce:**
1. Swap the `compose-bom` version [here](https://github.com/THEOplayer/android-ui/blob/main/gradle/libs.versions.toml#L8) with latest.
2. Build and run the project.
3. Try to hold and drag the progress bar to seek.

**Expected:**
Seek bar should function as expected when holding and dragging.

**Actual:**
Holding and dragging the seek bar doesn't work on the latest `compose-bom`. Short touching a certain position on the slider to seek still functions as expected though.

**Reproduction Rate:**
10/10.

**Device:**
Tested on Pixel 5 (Android 14)

https://github.com/THEOplayer/android-ui/assets/74964451/2fa8dee5-47a2-4aaa-86a6-8d1d50880e32

https://github.com/THEOplayer/android-ui/assets/74964451/2e8b47e7-1b7f-4096-b92a-e203042630b8

### PR DESCRIPTION
**Pull request by MattiasBuelens**
Fixes #24

### CODE REVIEW

File: ui/src/main/java/com/theoplayer/android/ui/SeekBar.kt [hunk 1]
```diff
@@ -27,32 +27,42 @@ fun SeekBar(
...
         },
-        onValueChangeFinished = {
-            seekTime = null
-            if (wasPlayingBeforeSeek) {
-                player?.player?.play()
-                wasPlayingBeforeSeek = false
+        // This needs to always be the *same* callback,
+        // otherwise Slider will reset its internal SliderState while dragging.
+        // https://github.com/androidx/androidx/blob/4d69c45e6361a2e5af77edc9f7f92af3d0db3877/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/Slider.kt#L270-L282
+        onValueChangeFinished = remember {
```
Comment (MattiasBuelens) [inline ui/src/main/java/com/theoplayer/android/ui/SeekBar.kt:59]: I'd say this is a regression in Compose Material 3. This used to work fine a year ago, and [all of the code samples](https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#Slider(kotlin.Float,kotlin.Function1,androidx.compose.ui.Modifier,kotlin.Boolean,kotlin.Function0,androidx.compose.material3.SliderColors,androidx.compose.foundation.interaction.MutableInteractionSource,kotlin.Int,kotlin.Function1,kotlin.Function1,kotlin.ranges.ClosedFloatingPointRange)) simply pass `onValueChangeFinished` directly.

I'll see if I can file an issue upstream... on Monday. First up: weekend! 😁

Comment (MattiasBuelens) [reply ui/src/main/java/com/theoplayer/android/ui/SeekBar.kt:59]: Ah, there's already [an open issue](https://issuetracker.google.com/u/1/issues/322269951) about it. And [one of the commenters found the same workaround](https://issuetracker.google.com/u/1/issues/322269951#comment8) by `remember`ing the callback. 🙂
